In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\axel_\Documents\conda\random-games\playerStats\csv\arsenal-vs-atletico-madrid.csv')
df.head()

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shirtNumber,positionId,usualPosition,...,recoveries,dribbled_past,duel_won,duel_lost,ground_duels_won_value,ground_duels_won_total,aerials_won_value,aerials_won_total,fouls_received,fouls_committed
0,Jan Oblak,177126,81352,9906,Atlético de Madrid,True,"[{'title': 'Top stats', 'key': 'top_stats', 's...",13,11.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Antoine Griezmann,184138,76650,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",7,104.0,3,...,0.0,1.0,4.0,2.0,2.0,4.0,2.0,2.0,1.0,0.0
2,Koke,184533,77390,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",6,74.0,2,...,9.0,0.0,3.0,1.0,2.0,2.0,1.0,2.0,1.0,0.0
3,Christian Nørgaard,266520,128295,9825,Arsenal,False,[],16,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Kepa Arrizabalaga,317564,109745,9825,Arsenal,True,[],13,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# list header rows
header_list = df.columns.tolist()
print(header_list)

['name', 'id', 'optaId', 'teamId', 'teamName', 'isGoalkeeper', 'stats', 'shirtNumber', 'positionId', 'usualPosition', 'matchId', 'matchRound', 'homeTeamName', 'homeTeamid', 'awayTeamName', 'awayTeamid', 'matchDate', 'home_goals', 'away_goals', 'FotMob_rating', 'Minutes_played', 'Goals', 'Assists', 'Total_shots', 'Accurate_passes_value', 'Accurate_passes_total', 'Chances_created', 'Expected_assists_xA', 'xG_plus_xA', 'Fantasy_points', 'Defensive_actions', 'touches', 'touches_opp_box', 'passes_into_final_third', 'accurate_crosses_value', 'accurate_crosses_total', 'long_balls_accurate_value', 'long_balls_accurate_total', 'dispossessed', 'tackles_succeeded_value', 'tackles_succeeded_total', 'shot_blocks', 'clearances', 'headed_clearance', 'interceptions', 'recoveries', 'dribbled_past', 'duel_won', 'duel_lost', 'ground_duels_won_value', 'ground_duels_won_total', 'aerials_won_value', 'aerials_won_total', 'fouls_received', 'fouls_committed']

In [6]:
# list header rows using list() function
header_list = list(df.columns)

# Using .values attribute
header_list = df.columns.values.tolist()
header_list

['name',
 'id',
 'optaId',
 'teamId',
 'teamName',
 'isGoalkeeper',
 'stats',
 'shirtNumber',
 'positionId',
 'usualPosition',
 'matchId',
 'matchRound',
 'homeTeamName',
 'homeTeamid',
 'awayTeamName',
 'awayTeamid',
 'matchDate',
 'home_goals',
 'away_goals',
 'FotMob_rating',
 'Minutes_played',
 'Goals',
 'Assists',
 'Total_shots',
 'Accurate_passes_value',
 'Accurate_passes_total',
 'Chances_created',
 'Expected_assists_xA',
 'xG_plus_xA',
 'Fantasy_points',
 'Defensive_actions',
 'touches',
 'touches_opp_box',
 'passes_into_final_third',
 'accurate_crosses_value',
 'accurate_crosses_total',
 'long_balls_accurate_value',
 'long_balls_accurate_total',
 'dispossessed',
 'tackles_succeeded_value',
 'tackles_succeeded_total',
 'shot_blocks',
 'clearances',
 'headed_clearance',
 'interceptions',
 'recoveries',
 'dribbled_past',
 'duel_won',
 'duel_lost',
 'ground_duels_won_value',
 'ground_duels_won_total',
 'aerials_won_value',
 'aerials_won_total',
 'fouls_received',
 'fouls_committed']

In [7]:
# list header rows
df.columns

Index(['name', 'id', 'optaId', 'teamId', 'teamName', 'isGoalkeeper', 'stats',
       'shirtNumber', 'positionId', 'usualPosition', 'matchId', 'matchRound',
       'homeTeamName', 'homeTeamid', 'awayTeamName', 'awayTeamid', 'matchDate',
       'home_goals', 'away_goals', 'FotMob_rating', 'Minutes_played', 'Goals',
       'Assists', 'Total_shots', 'Accurate_passes_value',
       'Accurate_passes_total', 'Chances_created', 'Expected_assists_xA',
       'xG_plus_xA', 'Fantasy_points', 'Defensive_actions', 'touches',
       'touches_opp_box', 'passes_into_final_third', 'accurate_crosses_value',
       'accurate_crosses_total', 'long_balls_accurate_value',
       'long_balls_accurate_total', 'dispossessed', 'tackles_succeeded_value',
       'tackles_succeeded_total', 'shot_blocks', 'clearances',
       'headed_clearance', 'interceptions', 'recoveries', 'dribbled_past',
       'duel_won', 'duel_lost', 'ground_duels_won_value',
       'ground_duels_won_total', 'aerials_won_value', 'aerials_won_total',
       'fouls_received', 'fouls_committed'],
      dtype='str')

In [8]:
# read each column
df[['name', 'teamName']].head()

                 name            teamName
0           Jan Oblak  Atlético de Madrid
1   Antoine Griezmann  Atlético de Madrid
2                Koke  Atlético de Madrid
3  Christian Nørgaard             Arsenal
4   Kepa Arrizabalaga             Arsenal

In [9]:
# Count how many times each team name appears
df['teamName'].value_counts()

teamName
Atlético de Madrid    23
Arsenal               23
Name: count, dtype: int64

In [12]:
# Or using groupby
df.groupby('teamName').size()

teamName
Arsenal               23
Atlético de Madrid    23
dtype: int64

In [16]:
# Group by name and show various statistics
grouped_stats = df.groupby('teamName').agg({
    'teamName': 'count',  # count occurrences
    # Add other columns you want to aggregate
}).rename(columns={'teamName': 'count'})

print(grouped_stats)

                    count
teamName
Arsenal                23
Atlético de Madrid     23

In [17]:
# See all unique names
df['teamName'].unique()

<StringArray>
['Atlético de Madrid', 'Arsenal']
Length: 2, dtype: str

In [18]:
# get row based on a specific condition
df.loc[df['teamName'] == 'Atlético de Madrid'].head(2)

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shirtNumber,positionId,usualPosition,...,recoveries,dribbled_past,duel_won,duel_lost,ground_duels_won_value,ground_duels_won_total,aerials_won_value,aerials_won_total,fouls_received,fouls_committed
0,Jan Oblak,177126,81352,9906,Atlético de Madrid,True,"[{'title': 'Top stats', 'key': 'top_stats', 's...",13,11.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Antoine Griezmann,184138,76650,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",7,104.0,3,...,0.0,1.0,4.0,2.0,2.0,4.0,2.0,2.0,1.0,0.0

In [61]:
# describe data
df.describe()

,id,optaId,teamId,shirtNumber,positionId,usualPosition,matchId,homeTeamid,awayTeamid,home_goals,...,recoveries,dribbled_past,duel_won,duel_lost,ground_duels_won_value,ground_duels_won_total,aerials_won_value,aerials_won_total,fouls_received,fouls_committed
count,4.600000e+01,46.000000,46.000000,46.000000,22.000000,46.000000,46.0,46.0,46.0,46.0,...,28.000000,28.000000,24.000000,26.000000,26.000000,26.000000,28.000000,28.000000,12.000000,28.000000
mean,8.883986e+05,331216.500000,9865.500000,18.239130,61.454545,1.565217,5205813.0,9906.0,9825.0,1.0,...,2.571429,0.571429,3.166667,2.923077,2.269231,4.538462,0.607143,1.214286,1.166667,0.642857
std,4.165558e+05,176660.157626,40.947527,16.756007,32.021908,0.958058,0.0,0.0,0.0,0.0,...,2.218250,0.790151,1.578846,1.572847,1.282426,2.231247,0.956045,1.066567,0.389249,0.826160
min,1.771260e+05,76650.000000,9825.000000,1.000000,11.000000,0.000000,5205813.0,9906.0,9825.0,1.0,...,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,5.827645e+05,193990.250000,9825.000000,7.000000,34.500000,1.000000,5205813.0,9906.0,9825.0,1.0,...,1.000000,0.000000,2.000000,1.250000,1.250000,3.000000,0.000000,0.000000,1.000000,0.000000
50%,9.488215e+05,241797.000000,9865.500000,14.000000,72.500000,1.500000,5205813.0,9906.0,9825.0,1.0,...,2.500000,0.000000,3.000000,3.000000,2.000000,4.000000,0.000000,1.000000,1.000000,0.000000
75%,1.213030e+06,488494.500000,9906.000000,21.750000,77.750000,2.000000,5205813.0,9906.0,9825.0,1.0,...,4.000000,1.000000,4.000000,4.000000,3.000000,6.000000,1.000000,2.000000,1.000000,1.000000
max,1.787525e+06,616077.000000,9906.000000,89.000000,107.000000,3.000000,5205813.0,9906.0,9825.0,1.0,...,9.000000,3.000000,7.000000,6.000000,5.000000,8.000000,4.000000,4.000000,2.000000,3.000000

In [31]:
# sort values
df.sort_values(['name', 'shirtNumber'], ascending=False).head()

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shirtNumber,positionId,usualPosition,...,recoveries,dribbled_past,duel_won,duel_lost,ground_duels_won_value,ground_duels_won_total,aerials_won_value,aerials_won_total,fouls_received,fouls_committed
22,Álex Baena,942372,248501,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",10,NaN,2,...,3.0,0.0,2.0,1.0,2.0,2.0,0.0,1.0,NaN,0.0
24,William Saliba,955406,462424,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",2,34.0,1,...,6.0,0.0,2.0,1.0,1.0,1.0,1.0,2.0,NaN,0.0
15,Viktor Gyökeres,664500,224117,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",14,105.0,3,...,1.0,0.0,5.0,2.0,1.0,3.0,4.0,4.0,1.0,3.0
35,Tommy Setford,1243239,551221,9825,Arsenal,True,[],35,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Thiago Almada,955271,461360,9906,Atlético de Madrid,False,[],11,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 56 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   name                       46 non-null     str
 1   id                         46 non-null     int64
 2   optaId                     46 non-null     int64
 3   teamId                     46 non-null     int64
 4   teamName                   46 non-null     str
 5   isGoalkeeper               46 non-null     bool
 6   stats                      46 non-null     str
 7   shirtNumber                46 non-null     int64
 8   positionId                 22 non-null     float64
 9   usualPosition              46 non-null     int64
 10  matchId                    46 non-null     int64
 11  matchRound                 46 non-null     str
 12  homeTeamName               46 non-null     str
 13  homeTeamid                 46 non-null     int64
 14  awayTeamName               46 non-null     str
 15  awayTeamid                 46 non-null     int64
 16  matchDate                  46 non-null     str
 17  home_goals                 46 non-null     int64
 18  away_goals                 46 non-null     int64
 19  FotMob_rating              28 non-null     float64
 20  Minutes_played             30 non-null     float64
 21  Goals                      28 non-null     float64
 22  Assists                    28 non-null     float64
 23  Total_shots                0 non-null      float64
 24  Accurate_passes_value      30 non-null     float64
 25  Accurate_passes_total      30 non-null     float64
 26  Chances_created            28 non-null     float64
 27  Expected_assists_xA        25 non-null     float64
 28  xG_plus_xA                 26 non-null     float64
 29  Fantasy_points             0 non-null      float64
 30  Defensive_actions          30 non-null     float64
 31  touches                    28 non-null     float64
 32  touches_opp_box            28 non-null     float64
 33  passes_into_final_third    22 non-null     float64
 34  accurate_crosses_value     10 non-null     float64
 35  accurate_crosses_total     10 non-null     float64
 36  long_balls_accurate_value  17 non-null     float64
 37  long_balls_accurate_total  17 non-null     float64
 38  dispossessed               28 non-null     float64
 39  tackles_succeeded_value    0 non-null      float64
 40  tackles_succeeded_total    0 non-null      float64
 41  shot_blocks                28 non-null     float64
 42  clearances                 28 non-null     float64
 43  headed_clearance           6 non-null      float64
 44  interceptions              28 non-null     float64
 45  recoveries                 28 non-null     float64
 46  dribbled_past              28 non-null     float64
 47  duel_won                   24 non-null     float64
 48  duel_lost                  26 non-null     float64
 49  ground_duels_won_value     26 non-null     float64
 50  ground_duels_won_total     26 non-null     float64
 51  aerials_won_value          28 non-null     float64
 52  aerials_won_total          28 non-null     float64
 53  fouls_received             12 non-null     float64
 54  fouls_committed            28 non-null     float64
 55  stats_parsed               46 non-null     object
dtypes: bool(1), float64(37), int64(10), object(1), str(7)
memory usage: 19.9+ KB

In [4]:
df['stats'][1]

"[{'title': 'Top stats', 'key': 'top_stats', 'stats': {'FotMob rating': {'key': 'rating_title', 'stat': {'value': 7.41, 'type': 'double'}}, 'Minutes played': {'key': 'minutes_played', 'stat': {'value': 90, 'type': 'integer'}}, 'Goals': {'key': 'goals', 'stat': {'value': 0, 'type': 'integer'}}, 'Assists': {'key': 'assists', 'stat': {'value': 0, 'type': 'integer'}}, 'Expected goals (xG)': {'key': 'expected_goals', 'stat': {'value': 0.46, 'type': 'double'}}, 'Expected goals on target (xGOT)': {'key': 'expected_goals_on_target_variant', 'stat': {'type': 'double'}}, 'Expected assists (xA)': {'key': 'expected_assists', 'stat': {'value': 0.14, 'type': 'double'}}, 'xG + xA': {'key': 'xg_and_xa', 'stat': {'value': 0.6000000000000001, 'type': 'double'}}, 'Accurate passes': {'key': 'accurate_passes', 'stat': {'value': 39, 'total': 48, 'type': 'fractionWithPercentage'}}, 'Chances created': {'key': 'chances_created', 'stat': {'value': 2, 'type': 'integer'}}, 'Shots on target': {'key': 'ShotsOnTarget', 'stat': {'value': 0, 'type': 'integer'}}, 'Shots off target': {'key': 'ShotsOffTarget', 'stat': {'value': 1, 'type': 'integer'}}, 'Blocked shots': {'key': 'blocked_shots', 'stat': {'value': 3, 'type': 'integer'}}, 'Shot accuracy': {'key': 'shot_accuracy', 'stat': {'value': 0, 'total': 1, 'type': 'fractionWithPercentage'}}, 'Shotmap': {'key': None, 'stat': {'value': 1, 'type': 'boolean'}}, 'Defensive actions': {'key': 'defensive_actions', 'stat': {'value': 2, 'type': 'integer'}}}}, {'title': 'Attack', 'key': 'attack', 'stats': {'Hit woodwork': {'key': 'shots_woodwork', 'stat': {'value': 1, 'type': 'integer'}}, 'Touches': {'key': 'touches', 'stat': {'value': 62, 'type': 'integer'}}, 'Touches in opposition box': {'key': 'touches_opp_box', 'stat': {'value': 5, 'type': 'integer'}}, 'Passes into final third': {'key': 'passes_into_final_third', 'stat': {'value': 3, 'type': 'integer'}}, 'Accurate crosses': {'key': 'accurate_crosses', 'stat': {'value': 2, 'total': 5, 'type': 'fractionWithPercentage'}}, 'Accurate long balls': {'key': 'long_balls_accurate', 'stat': {'value': 1, 'total': 3, 'type': 'fractionWithPercentage'}}, 'Corners': {'key': 'corners', 'stat': {'value': 3, 'type': 'integer'}}, 'Dispossessed': {'key': 'dispossessed', 'stat': {'value': 1, 'type': 'integer'}}, 'xG Non-penalty': {'key': 'expected_goals_non_penalty', 'stat': {'value': 0.46, 'type': 'double'}}}}, {'title': 'Defense', 'key': 'defense', 'stats': {'Defensive actions': {'key': 'defensive_actions', 'stat': {'value': 2, 'type': 'integer'}}, 'Tackles': {'key': 'matchstats.headers.tackles', 'stat': {'value': 1, 'type': 'integer'}}, 'Blocks': {'key': 'shot_blocks', 'stat': {'value': 0, 'type': 'integer'}}, 'Clearances': {'key': 'clearances', 'stat': {'value': 1, 'type': 'integer'}}, 'Headed clearance': {'key': 'headed_clearance', 'stat': {'value': 1, 'type': 'integer'}}, 'Interceptions': {'key': 'interceptions', 'stat': {'value': 0, 'type': 'integer'}}, 'Recoveries': {'key': 'recoveries', 'stat': {'value': 0, 'type': 'integer'}}, 'Dribbled past': {'key': 'dribbled_past', 'stat': {'value': 1, 'type': 'integer'}}}}, {'title': 'Duels', 'key': 'duels', 'stats': {'Ground duels won': {'key': 'ground_duels_won', 'stat': {'value': 2, 'total': 4, 'type': 'fractionWithPercentage'}}, 'Aerial duels won': {'key': 'aerials_won', 'stat': {'value': 2, 'total': 2, 'type': 'fractionWithPercentage'}}, 'Was fouled': {'key': 'was_fouled', 'stat': {'value': 1, 'type': 'integer'}}, 'Fouls committed': {'key': 'fouls', 'stat': {'value': 0, 'type': 'integer'}}, 'Duels won': {'key': 'duel_won', 'stat': {'value': 4, 'type': 'integer'}, 'hideInPopupCard': True}, 'Duels lost': {'key': 'duel_lost', 'stat': {'value': 2, 'type': 'integer'}, 'hideInPopupCard': True}}}]"

In [3]:
import json
import ast

In [4]:
# convert stats column to dict
df['stats_parsed'] = df['stats'].apply(ast.literal_eval)

In [7]:
df.head(1)

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shirtNumber,positionId,usualPosition,...,dribbled_past,duel_won,duel_lost,ground_duels_won_value,ground_duels_won_total,aerials_won_value,aerials_won_total,fouls_received,fouls_committed,stats_parsed
0,Jan Oblak,177126,81352,9906,Atlético de Madrid,True,"[{'title': 'Top stats', 'key': 'top_stats', 's...",13,11.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'title': 'Top stats', 'key': 'top_stats', 's..."

In [6]:
# xG
df['stats_parsed'][1][0]['stats']['Expected goals (xG)']['stat']['value']

0.46

In [5]:
# xG
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Expected goals (xG)']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['xG'] = df['stats_parsed'].apply(extract)

In [ ]:
# xGOT
df['stats_parsed'][1][0]['stats']['Expected goals on target (xGOT)']['stat']['value']

IndexError: list index out of range

In [7]:
# xGOT
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Expected goals on target (xGOT)']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['xGOT'] = df['stats_parsed'].apply(extract)

In [8]:
# Shots on target
df['stats_parsed'][1][0]['stats']['Shots on target']['stat']['value']

0

In [9]:
# Shots on target
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Shots on target']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['shots_on_target'] = df['stats_parsed'].apply(extract)

In [10]:
# Shots off target
df['stats_parsed'][1][0]['stats']['Shots off target']['stat']['value']

1

In [11]:
# Shots off target
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Shots off target']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['shots_off_target'] = df['stats_parsed'].apply(extract)

In [12]:
# Blocked shots
df['stats_parsed'][1][0]['stats']['Blocked shots']['stat']['value']

3

In [13]:
# Blocked shots
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Blocked shots']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['blocked_shots'] = df['stats_parsed'].apply(extract)

In [14]:
# Shot accuracy
df['stats_parsed'][1][0]['stats']['Shot accuracy']['stat']['value']

0

In [15]:
# Shot accuracy
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Shot accuracy']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['shot_accuracy'] = df['stats_parsed'].apply(extract)

In [16]:
# Hit woodwork 
df['stats_parsed'][1][1]['stats']['Hit woodwork']['stat']['value']

1

In [17]:
# Hit woodwork
def extract(stats_parsed):
    try:
        return stats_parsed[1]['stats']['Hit woodwork']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['hit_woodwork'] = df['stats_parsed'].apply(extract)

In [18]:
# Corners
df['stats_parsed'][1][1]['stats']['Corners']['stat']['value']

3

In [19]:
# corners
def extract(stats_parsed):
    try:
        return stats_parsed[1]['stats']['Corners']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['corners'] = df['stats_parsed'].apply(extract)

In [20]:
# xG non penalty
df['stats_parsed'][1][1]['stats']['xG Non-penalty']['stat']['value']

0.46

In [21]:
# xG non penalty
def extract(stats_parsed):
    try:
        return stats_parsed[1]['stats']['xG Non-penalty']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['xG_non_penalty'] = df['stats_parsed'].apply(extract)

In [22]:
# tackles
df['stats_parsed'][1][2]['stats']['Tackles']['stat']['value']

1

In [23]:
# tackles
def extract(stats_parsed):
    try:
        return stats_parsed[2]['stats']['Tackles']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['tackles'] = df['stats_parsed'].apply(extract)

In [24]:
# shot_blocks
df['stats_parsed'][1][2]['stats']['Blocks']['stat']['value']

0

In [25]:
# shot_blocks
def extract(stats_parsed):
    try:
        return stats_parsed[2]['stats']['Blocks']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['shot_blocks'] = df['stats_parsed'].apply(extract)

In [26]:
# goal keeper saves
df['stats_parsed'][0][0]['stats']['Saves']['stat']['value']

1

In [27]:
# goal keeper saves
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Saves']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_saves'] = df['stats_parsed'].apply(extract)

In [28]:
# goal keeper goals conceded
df['stats_parsed'][0][0]['stats']['Goals conceded']['stat']['value']

1

In [29]:
# goal keeper goals conceded
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Goals conceded']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_goals_conceded'] = df['stats_parsed'].apply(extract)

In [30]:
# goal keeper xGOT faced
df['stats_parsed'][0][0]['stats']['xGOT faced']['stat']['value']

0.7

In [31]:
# goal keeper xGOT faced
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['xGOT faced']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_xGOT_faced'] = df['stats_parsed'].apply(extract)

In [32]:
# goal keeper goals prevented
df['stats_parsed'][0][0]['stats']['Goals prevented']['stat']['value']

-0.3

In [33]:
# goal keeper goals prevented
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Goals prevented']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_goals_prevented'] = df['stats_parsed'].apply(extract)

In [34]:
# goal keeper diving save
df['stats_parsed'][0][0]['stats']['Diving save']['stat']['value']

0

In [35]:
# goal keeper diving save
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Diving save']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_diving_save'] = df['stats_parsed'].apply(extract)

In [ ]:
# goal keeper saves inside box
df['stats_parsed'][0][0]['stats']['Saves inside box']['stat']['value']

0

In [39]:
# goal keeper saves inside box
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Saves inside box']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_saves_inside_box'] = df['stats_parsed'].apply(extract)

In [ ]:
# goal keeper acted as sweeper
df['stats_parsed'][0][0]['stats']['Acted as sweeper']['stat']['value']

2

In [43]:
# goal keeper acted as sweeper
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Acted as sweeper']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_acted_as_sweeper'] = df['stats_parsed'].apply(extract)

In [49]:
# goal keeper punches
df['stats_parsed'][0][0]['stats']['Punches']['stat']['value']

0

In [54]:
# goal keeper punches
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Punches']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_punches'] = df['stats_parsed'].apply(extract)

In [ ]:
# goal keeper throws
df['stats_parsed'][0][0]['stats']['Throws']['stat']['value']

3

In [55]:
# goal keeper throws
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['Throws']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_throws'] = df['stats_parsed'].apply(extract)

In [ ]:
# goal keeper high claim
df['stats_parsed'][0][0]['stats']['High claim']['stat']['value']

0

In [60]:
# goal keeper high claim
def extract(stats_parsed):
    try:
        return stats_parsed[0]['stats']['High claim']['stat']['value']
    except (KeyError, IndexError, TypeError):
        return None  # or np.nan

df['gk_high_claim'] = df['stats_parsed'].apply(extract)

In [68]:
# Save to CSV
df.to_csv(r'C:\Users\axel_\Documents\conda\random-games\playerStats\csv\arsenal-vs-atletico-madrid-v1.csv', index=False)

In [69]:
c_df = pd.read_csv(r'C:\Users\axel_\Documents\conda\random-games\playerStats\csv\arsenal-vs-atletico-madrid-v1.csv')
c_df

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shirtNumber,positionId,usualPosition,...,gk_saves,gk_goals_conceded,gk_xGOT_faced,gk_goals_prevented,gk_diving_save,gk_saves_inside_box,gk_acted_as_sweeper,gk_punches,gk_throws,gk_high_claim
0,Jan Oblak,177126,81352,9906,Atlético de Madrid,True,"[{'title': 'Top stats', 'key': 'top_stats', 's...",13,11.0,0,...,1.0,1.0,0.70,-0.30,0.0,0.0,2.0,0.0,3.0,0.0
1,Antoine Griezmann,184138,76650,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",7,104.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Koke,184533,77390,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",6,74.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Christian Nørgaard,266520,128295,9825,Arsenal,False,[],16,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Kepa Arrizabalaga,317564,109745,9825,Arsenal,True,[],13,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Leandro Trossard,318615,116216,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",19,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Juan Musso,389050,121537,9906,Atlético de Madrid,True,[],1,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alexander Sørloth,440330,143877,9906,Atlético de Madrid,False,[],9,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Clément Lenglet,488412,171101,9906,Atlético de Madrid,False,[],15,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Martin Ødegaard,534670,184029,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",8,73.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,David Raya,562727,154561,9825,Arsenal,True,"[{'title': 'Top stats', 'key': 'top_stats', 's...",1,11.0,0,...,3.0,1.0,1.79,0.79,2.0,2.0,1.0,1.0,6.0,1.0
11,Gabriel Jesus,576165,205651,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",9,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Marcos Llorente,602563,192364,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",14,32.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Robin Le Normand,609516,224919,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",24,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Declan Rice,654096,204480,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",41,77.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Viktor Gyökeres,664500,224117,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",14,105.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Ademola Lookman,690516,219352,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",22,78.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Nahuel Molina,726345,221586,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",16,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Dávid Hancko,727897,235093,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",17,36.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Ben White,776151,198869,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",4,32.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Gabriel,795179,226597,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",6,36.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Eberechi Eze,818975,232413,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",10,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Álex Baena,942372,248501,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",10,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Thiago Almada,955271,461360,9906,Atlético de Madrid,False,[],11,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,William Saliba,955406,462424,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",2,34.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Bukayo Saka,961995,223340,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",7,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Julián Álvarez,974753,461358,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",19,106.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Gabriel Martinelli,1021586,444145,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",11,107.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Martín Zubimendi,1031325,481655,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",36,75.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Matteo Ruggeri,1051097,487992,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",3,38.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Noni Madueke,1084981,248857,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",20,103.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Riccardo Calafiori,1105912,466075,9825,Arsenal,False,[],33,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Piero Hincapié,1137667,448104,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",5,38.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Johnny Cardoso,1173678,488662,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",5,76.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Giuliano Simeone,1226147,482652,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",20,72.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Tommy Setford,1243239,551221,9825,Arsenal,True,[],35,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Obed Vargas,1254394,502868,9906,Atlético de Madrid,False,[],21,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Cristhian Mosquera,1298907,500040,9825,Arsenal,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",3,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Marc Pubill,1323897,562720,9906,Atlético de Madrid,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",18,34.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Javier Boñar,1367926,551310,9906,Atlético de Madrid,False,[],32,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Myles Lewis-Skelly,1406436,499169,9825,Arsenal,False,[],49,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Rodrigo Mendoza,1419969,578538,9906,Atlético de Madrid,False,[],4,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Julio Díaz,1447089,551311,9906,Atlético de Madrid,False,[],34,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Salvi Esquivel,1553402,551321,9906,Atlético de Madrid,True,[],31,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Max Dowman,1635773,616077,9825,Arsenal,False,[],56,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Marli Salmon,1787525,616065,9825,Arsenal,False,[],89,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN